name: ctrl_alt_foo
version: 0.2.0
description: For creating simple keyboard shortcuts.
authors:
- Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/ctrl-alt-foo
dev_dependencies:
  unittest: any
