name: ctrl_alt_foo
version: 0.0.1
description: Keyboard library to make keyboard events in Dart a pleasure.
authors:
- Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/ctrl-alt-foo
dependencies:
  unittest: ">=0.6.15+3 <0.6.16"
  js: ">=0.0.24 <0.0.25"
