name: ctrl_alt_foo2
version: 0.4.0
description: For creating simple keyboard shortcuts.
authors:
- Chris Strom <chris@eeecomputes.com>
- Daisuke Yamashita <dddaisuke@gmail.com>
homepage: https://github.com/dddaisuke/ctrl-alt-foo
environment:
  sdk: '2.7.1'
